#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Oct 28 21:57:09 2008

import ConfigParser

class Config():
    """The configuration stored in a config file"""
    def __init__(self, configfile):
        self.parser = ConfigParser.ConfigParser()
        self.configfile = configfile
        self.setDefault()
        self.readOptions()

    def setDefault(self):
        """Initialize with default values"""
        self.options = {
            'projects' : ['/data/Dropbox/programming/EP_report2/ep_report'],
            'default_project' : 0
            }
        

    def readOptions(self):
        try:
            self.parser.read(self.configfile)
            for key in self.options:
                self.options[key] = self.parser.get('options', key)

        except: # if file is not present or is damaged
            return # donot change defaults
            

    def writeOptions(self):
        try:
            self.parser.add_section('options')
        except:
            pass # section already exists
            
        for key in self.options:
            self.parser.set('options', key, self.options[key])

        self.parser.write(open(self.configfile, 'w'))

